---
title: "Finantials"
output: html_document
date: "2025-10-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, include = TRUE, cache = FALSE, results = 'asis', warning = FALSE)
library(dplyr)
#library(neo4r)
library(visNetwork)
library(bolt4jr)
library(reticulate)
library(here)

use_virtualenv("~/.venvs/neo4j_env", required = TRUE)

user_neo4j <- "neo4j"
password_neo4j <- "norpentar"

```



Tabla de variables financieras por empresas.

```{r}
source("./run.R")
```


Valor en monedas nacionales y en dólares, ajustados a 1990.

```{r}
tabla <- lista_empresas_principales$tablaFinancialsEmpresas() %>% select(-valor_ajustado) %>% pivot_wider(names_from = anho, values_from = valor)

for (var in unique(tabla$variable)){
  tabla_aux <- tabla %>% filter(variable==var)
  var <- gsub(" ", "_", var)
  ruta <- here("export","tablas","financials","variables","currency_nacional",paste("tabla_variables_",var,"_currency_nacional.csv",sep=""))
  write.csv(tabla_aux, file = ruta)
}

tabla <- lista_empresas_principales$tablaFinancialsEmpresas() %>% select(-valor) %>% pivot_wider(names_from = anho, values_from = valor_ajustado)

for (var in unique(tabla$variable)){
  tabla_aux <- tabla %>% filter(variable==var)
  ruta <- here("export","tablas","financials","variables","usd_2023",paste("tabla_variables_",var,"_usd_2023.csv",sep=""))
  write.csv(tabla_aux, file = ruta)
}
```


